name: "DNS-DHCP Server"
version: "1.0.11"
slug: "dns-dhcp"
description: "Home Assistant DNS-DHCP"
url: "https://github.com/Jorre05/ha_dns_dhcp_addon"
arch:
  - aarch64
  - amd64
init: false
host_network: true
ports:
  53/udp: 53
  53/tcp: 53
  67/udp: 67
map:
  - addon_config:rw 
  - share:rw
backup_exclude:
  - '*/cache'
