name: "DNS-DHCP Server"
version: "1.0.9"
slug: "dns-dhcp"
description: "Home Assistant DNS-DHCP"
url: "https://github.com/Jorre05/ha_dns_dhcp_addon"
arch:
  - aarch64
  - amd64
init: false
ports:
  53/udp: 1053
  53/tcp: 1053
  67/udp: 1067
map:
  - addon_config:rw 
  - share:rw
backup_exclude:
  - '*/cache'
