name: "DNS-DHCP Server"
version: "1.0.7"
slug: "dns-dhcp"
description: "Home Assistant DNS-DHCP"
url: "https://github.com/Jorre05/ha_dns_dhcp_addon"
arch:
  - aarch64
  - amd64
init: false
ports:
  1053/udp: 53
  1053/tcp: 53
  1067/udp: 67
map:
  - addon_config:rw 
  - share:rw
options:
  interface: "etho"
schema:
  interface: "str?"
backup_exclude:
  - '*/cache'
