name: "DNS-DHCP Server"
version: "1.0.0"
slug: "dns-dhcp"
description: "Home Assistant DNS-DHCP"
url: "https://github.com/Jorre05/ha_dns_dhcp_addon"
arch:
  - aarch64
  - amd64
init: false
ports:
  53/udp: 53
  53/tcp: 53
map:
  - addon_config:rw 
  - share:rw
image: ghcr.io/cmsj/{arch}-ha-dns-dhcp-addon
options:
  interface: "etho"
schema:
  interface: "str?"
backup_exclude:
  - '*/cache'
